apiVersion: v1
kind: Service
metadata:
  name: sib-frontend-service
  labels:
    run: sib-frontend
spec:
  ports:
    - port: 3001
      protocol: TCP
  selector:
    app: sib-frontend
  type: NodePort
