apiVersion: v1
kind: Service
metadata:
  name: sib-contract-service-service
  labels:
    run: sib-contract-service
spec:
  ports:
    - port: 3002
      protocol: TCP
  selector:
    app: sib-contract-service
  type: NodePort
