apiVersion: apps/v1
kind: Deployment
metadata:
  name: sib-contract-service-deploy
  labels:
    app: sib-contract-service
  annotations:
spec:
  selector:
    matchLabels:
      app: sib-contract-service
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: sib-contract-service
    spec:
      containers:
        - name: sib-contract-service
          env:
            - name: ACCESS_TOKEN_SECRET
              value: "8242545801755761506376408302163326328803538689829747727040587833343463956932020309503098520983720859"
          image: meshkat/sib-contract-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "500m"
